TECHNOLOGIES = [
    "Flask",
    "Django",
    "FastAPI",
    "RESTful APIs",
    "JavaScript",
    "React",
    "Angular",
    "Vue.js",
    "HTML/CSS",
    "SQLAlchemy",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Docker",
    "Kubernetes",
    "AWS (Amazon Web Services)",
    "Azure",
    "Git/GitHub",
    "Jenkins",
    "CircleCI",
    "Unit Testing",
    "Selenium",
    "Celery",
    "Redis",
    "GraphQL",
    "Pyramid",
    "Tornado",
    "WebSockets",
    "GraphQL",
    "REST",
    "Microservices",
    "OAuth",
    "JWT",
    "Bootstrap",
    "Tailwind CSS",
    "Scrapy",
    "Beautiful Soup",
    "Machine Learning",
    "NumPy",
    "Pandas",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Matplotlib",
    "Seaborn",
    "Plotly",
    "Jupyter Notebooks",
    "Pytest",
]
